service: app-monitoring-archiver

frameworkVersion: ^3.2.0

provider:
  name: aws
  runtime: provided.al2
  timeout: 600
  versionFunctions: false
  memorySize: 128
  logRetentionInDays: 14

  environment:
    namespace: ${self:custom.namespace}
    NODEPING_TOKEN: ${env:NODEPING_TOKEN}
    GOOGLE_AUTH_CLIENT_EMAIL: ${env:GOOGLE_AUTH_CLIENT_EMAIL}
    GOOGLE_AUTH_PRIVATE_KEY_ID: ${env:GOOGLE_AUTH_PRIVATE_KEY_ID}
    GOOGLE_AUTH_PRIVATE_KEY: ${env:GOOGLE_AUTH_PRIVATE_KEY}
    GOOGLE_AUTH_TOKEN_URI: ${env:GOOGLE_AUTH_TOKEN_URI}

custom:
  prod:
    # cron(Minutes Hours Day-of-month Month Day-of-week Year)
    schedule: cron(30 3 1 * ? *)
  dev:
    schedule: cron(40 14 1,20 * ? *)
  namespace: ${self:service}_${sls:stage}

package:
  patterns:
  - '!./**'
  - './bootstrap'

functions:
  archiveToGoogleSheets:
    handler: bootstrap
    events:
    - schedule:
        rate: ${self:custom.${sls:stage}.schedule}
        input:
          ContactGroupName: ${env:CONTACT_GROUP_NAME}
          CountLimit: ${env:COUNT_LIMIT}
          Period: ${env:PERIOD}
          SpreadSheetID: ${env:SPREADSHEET_ID}
