name: Continuous Integration

on:
  push:

jobs:
  test-and-deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Unit tests
        run: go test -v ./lib/googlesheets/...

      - name: Deploy
        if: github.ref_name == 'main' || github.ref_name == 'develop'
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: docker-compose -f action-services.yml run deploy
