name: scheduled govulncheck scan
on:
  schedule:
    - cron: '15 6 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  govulncheck:
    uses: sil-org/workflows/.github/workflows/govulncheck.yaml@main
    with:
      check-latest: false
      go-version-file: './go.mod'
      go-version-input: ''
      work-dir: '.'
      aws-region: ${{ vars.AWS_REGION }}
      aws-role: ${{ vars.AWS_CD_ROLE_ARN }}
      from-email: gtis_itse_alerts@groups.sil.org
      to-email: gtis_itse_support+notifications@sil.org
